apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
spec:
  template:
    metadata:
      annotations:
        prometheus.io/path: /api/v1/metrics/prometheus
        prometheus.io/port: "2020"
        prometheus.io/scrape: "true"
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: fluentbit
      hostNetwork: true
      containers:
      - name: fluentbit
        image: fluent/fluent-bit:1.7.4-debug
        envFrom:
        - configMapRef:
            name: fluentbit-env
        resources:
          limits:
            memory: 1500Mi
          requests:
            cpu: 500m
            memory: 500Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          readOnly: true
          mountPath: /var/lib/docker/containers
        - name: fluentbit-config
          mountPath: /fluent-bit/etc/
        - name: fluentbit-storage
          mountPath: /var/log/flb-storage/
        imagePullPolicy: Always
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentbit-config
        configMap:
          name: fluentbit-config
      - name: fluentbit-storage
        hostPath:
          path: /var/log/flb-storage/
