apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- daemonset.yaml
- rbac.yaml
commonLabels:
  app.kubernetes.io/name: fluentbit
configMapGenerator:
- name: fluentbit-env
  literals:
  - ELASTICSEARCH_HOST=elasticsearch.example.com # {"$kpt-set":"outputs.elasticsearch.host-subst"}
  - ELASTICSEARCH_PORT=443
  - ELASTICSEARCH_AWS_AUTH=Off # {"$kpt-set":"outputs.elasticsearch.aws.auth-subst"}
  - ELASTICSEARCH_AWS_REGION=us-gov-west-1 # {"$kpt-set":"outputs.elasticsearch.aws.region-subst"}
  - S3_BUCKET_NAME=access-logs # {"$kpt-set":"outputs.s3.bucket.name-subst"}
  - S3_BUCKET_KEY_FORMAT="/%Y/%m/%d/access-logs-%Y%m%d%H%M-$UUID.log" # {"$kpt-set":"outputs.s3.bucket.key-format-subst"}
  - S3_BUCKET_REGION=us-gov-west-1 # {"$kpt-set":"outputs.s3.bucket.region-subst"}
- name: fluentbit-config
  files:
  - config/fluent-bit.conf
  - config/parsers.conf
  - config/input-kubernetes.conf
  - config/filter-kubernetes.conf
  - config/filter-aws.conf
  - config/output-elasticsearch.conf
  - config/output-s3.conf
