apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit
  annotations:
    eks.amazonaws.com/role-arn: "" # kpt-set: ${aws.role-arn}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentbit
rules:
- resources:
  - namespaces
  - pods
  - nodes
  - nodes/proxy
  apiGroups: [""]
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentbit
roleRef:
  name: fluentbit
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: fluentbit
  kind: ServiceAccount
