nameReference:
- kind: Service
  version: v1
  fieldSpecs:
    - kind: CustomResourceDefinition
      group: apiextensions.k8s.io
      path: spec/conversion/webhook/clientConfig/service/name

namespace:
- kind: CustomResourceDefinition
  group: apiextensions.k8s.io
  path: spec/conversion/webhook/clientConfig/service/namespace
  create: false

varReference:
- path: webhooks/namespaceSelector/matchExpressions/values
  kind: ValidatingWebhookConfiguration