apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory # {"$kpt-set":"issuer"}
    email: "user@example.com" # {"$kpt-set":"email"}
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
