apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../upstream

resources:
- ../default-issuer/cluster-issuer.yaml

patches:
- patch: ../default-issuer/deployment-patch.json
  target:
    kind: Deployment
    name: cert-manager
