apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: appdat-system 

configurations:
  - configurations.yaml

bases:
- ../upstream

components:
- ../default-issuer

vars:
- name: WEBHOOK_DEPLOYMENT_NAME
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: cert-manager-webhook
  fieldref:
    fieldpath: metadata.name
- name: WEBHOOK_DEPLOYMENT_NAMESPACE
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: cert-manager-webhook
  fieldref:
    fieldpath: metadata.namespace

patches:
- patch: |-
    - op: replace
      path: "/metadata/annotations/cert-manager.io~1inject-ca-from-secret"
      value: $(WEBHOOK_DEPLOYMENT_NAMESPACE)/$(WEBHOOK_DEPLOYMENT_NAME)-ca
  target:
    annotationSelector: "cert-manager.io/inject-ca-from-secret"
- patch: |-
    - op: replace
      path: "/spec/template/spec/containers/0/args/3"
      value: --dynamic-serving-ca-secret-name=$(WEBHOOK_DEPLOYMENT_NAME)-ca
    - op: replace
      path: "/spec/template/spec/containers/0/args/4"
      value: --dynamic-serving-dns-names=$(WEBHOOK_DEPLOYMENT_NAME),$(WEBHOOK_DEPLOYMENT_NAME).$(WEBHOOK_DEPLOYMENT_NAMESPACE),$(WEBHOOK_DEPLOYMENT_NAME).$(WEBHOOK_DEPLOYMENT_NAMESPACE).svc
  target:
    kind: Deployment
    name: cert-manager-webhook
- patch: |-
    - op: replace
      path: "/webhooks/0/namespaceSelector/matchExpressions/1/values/0"
      value: $(WEBHOOK_DEPLOYMENT_NAMESPACE)
  target:
    kind: ValidatingWebhookConfiguration
    name: cert-manager-webhook
