apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
resources:
- cert-manager
- ingress-nginx
- mongodb-kubernetes-operator
