apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: add-local-config-annotation
source: |
  managedBy = "app.kubernetes.io/managed-by"
  print(ctx)
  for resource in ctx.resource_list["items"]:
    if resource.get('apiVersion', '').startswith("kustomize.config.k8s.io"):
      if 'metadata' not in resource:
        resource['metadata'] = {}
      
      if 'annotations' not in resource['metadata']:
        resource['metadata']['annotations'] = {}
      
      resource['metadata']['annotations']['config.kubernetes.io/local-config'] = "true"
