apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: appdat-system # {"$kpt-set":"namespace"}
resources:
- ../upstream
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: ingress-nginx-custom-add-headers
  behavior: create
  literals:
  - Referrer-Policy=strict-origin-when-cross-origin
  - X-Using-Nginx-Controller="true"
# https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
- name: ingress-nginx-controller
  behavior: merge
  literals:
  - add-headers=appdat-system/ingress-nginx-custom-add-headers # {"$kpt-set":"headers-config-path"}
  - enable-modsecurity="true"
  - enable-vts-status="true"
  - generate-request-id="true"
  - hsts-include-subdomains="true"
  - hsts-max-age="31536000"
  - hsts-preload="true"
  - hsts="true"
  - log-format-escape-json="true"
  - server-tokens="false"
  - ssl-ciphers=ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4
  - ssl-protocols=TLSv1.2 TLSv1.3
  files:
  - log-format-upstream=log-format-upstream.json
patches:
- patch: |-
    - op: replace
      path: /spec/externalTrafficPolicy
      value: Cluster
  target:
    kind: Service
    name: ingress-nginx-controller
- patch: |-
    - op: replace
      path: /kind
      value: DaemonSet
  target:
    kind: Deployment
    name: ingress-nginx-controller
