apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../upstream

configMapGenerator:
- name: ingress-nginx-custom-add-headers
  namespace: ingress-nginx
  behavior: create
  options:
    disableNameSuffixHash: true
  literals:
  - Referrer-Policy=strict-origin-when-cross-origin
  - X-Using-Nginx-Controller="true"

- name: ingress-nginx-controller
  namespace: ingress-nginx
  behavior: merge
  literals:
  - add-headers=ingress-nginx/ingress-nginx-custom-add-headers
  - enable-modsecurity="true"
  - enable-vts-status="true"
  - generate-request-id="true"
  - hsts-include-subdomains="true"
  - hsts-max-age="31536000"
  - hsts-preload="true"
  - hsts="true"
  - log-format-escape-json="true"
  - real-ip-header=proxy_protocol
  - server-tokens="false"
  - ssl-ciphers=ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4
  - ssl-protocols=TLSv1.2 TLSv1.3
  - use-proxy-protocol="true"
  files:
  - log-format-upstream=log-format-upstream.json

patches:
- patch: |-
    - op: replace
      path: /spec/externalTrafficPolicy
      value: Cluster
  target:
    kind: Service
    name: ingress-nginx-controller
    namespace: ingress-nginx
- patch: |-
    - op: replace
      path: /kind
      value: DaemonSet
  target:
    kind: Deployment
    name: ingress-nginx-controller
    namespace: ingress-nginx
