apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
namespace: ingress-nginx
configMapGenerator:
# https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
- name: ingress-nginx-controller
  namespace: ingress-nginx
  behavior: merge
  literals:
  - log-format-escape-json="true"
  files:
  - log-format-upstream=log-format.json
generatorOptions:
  disableNameSuffixHash: true
