helmCharts:
- name: cert-manager
  releaseName: cert-manager
  namespace: cert-manager
  repo: https://charts.jetstack.io
  version: 1.6.1
  valuesInline:
    global:
      leaderElection:
        namespace: cert-manager
    installCRDs: true
