apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
---
# TODO: determine what permissions are necessary, doesn't seem like these should be needed but they came from...
# source: https://github.com/elastic/cloud-on-k8s/blob/1.6/config/recipes/beats/filebeat_autodiscover.yaml#L64-L77
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  - nodes
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
