nameReference:
- kind: Elasticsearch
  group: elasticsearch.k8s.elastic.co
  fieldSpecs:
  - kind: Kibana
    group: kibana.k8s.elastic.co
    path: spec/elasticsearchRef/name
  - kind: Beat
    group: beat.k8s.elastic.co
    path: spec/elasticsearchRef/name

- kind: Kibana
  group: kibana.k8s.elastic.co
  version: v1
  fieldSpecs:
  - kind: Beat
    group: beat.k8s.elastic.co
    path: spec/kibanaRef/name
