nameReference:
- kind: Secret
  version: v1
  fieldSpecs:
  - kind: ClusterIssuer
    group: cert-manager.io
    version: v1
    path: spec/acme/privateKeySecretRef/name
  - kind: Issuer
    group: cert-manager.io
    version: v1
    path: spec/acme/privateKeySecretRef/name
varReference:
- path: webhooks/namespaceSelector/matchExpressions/values
  kind: ValidatingWebhookConfiguration
