# Source: cert-manager/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
  namespace: "appdat-system" # {"$kpt-set":"namespace"}
  labels:
    app: cert-manager
    app.kubernetes.io/component: "controller"
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cert-manager
    helm.sh/chart: cert-manager-v1.2.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: "controller"
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/name: cert-manager
  template:
    metadata:
      labels:
        app: cert-manager
        app.kubernetes.io/component: "controller"
        app.kubernetes.io/instance: cert-manager
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: cert-manager
        helm.sh/chart: cert-manager-v1.2.0
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: '9402'
        prometheus.io/scrape: 'true'
    spec:
      serviceAccountName: cert-manager
      containers:
      - name: cert-manager
        image: "quay.io/jetstack/cert-manager-controller:v1.2.0"
        args:
        - --v=2
        - --cluster-resource-namespace=$(POD_NAMESPACE)
        - --leader-election-namespace=kube-system
        ports:
        - protocol: TCP
          containerPort: 9402
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources: {}
        imagePullPolicy: IfNotPresent
