# Source: cert-manager/templates/webhook-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook
  namespace: "appdat-system" # {"$kpt-set":"namespace"}
  labels:
    app: webhook
    app.kubernetes.io/component: "webhook"
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: webhook
    helm.sh/chart: cert-manager-v1.2.0
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: "webhook"
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: webhook
  ports:
  - name: https
    port: 443
    targetPort: 10250
