# Source: cert-manager/templates/webhook-validating-webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: cert-manager-webhook
  labels:
    app: webhook
    app.kubernetes.io/component: "webhook"
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: webhook
    helm.sh/chart: cert-manager-v1.2.0
  annotations:
    cert-manager.io/inject-ca-from-secret: "appdat-system/cert-manager-webhook-ca" # {"$kpt-set":"webhook-ca"}
webhooks:
- name: webhook.cert-manager.io
  admissionReviewVersions: ["v1", "v1beta1"]
  clientConfig:
    service:
      name: cert-manager-webhook
      namespace: "appdat-system" # {"$kpt-set":"namespace"}
      path: /validate
  failurePolicy: Fail
  namespaceSelector:
    matchExpressions:
    - key: "cert-manager.io/disable-validation"
      operator: "NotIn"
      values:
      - "true"
    - key: "name"
      operator: "NotIn"
      values:
      - appdat-system # {"$kpt-set":"namespace"}
  rules:
  - resources:
    - "*/*"
    apiGroups:
    - "cert-manager.io"
    - "acme.cert-manager.io"
    apiVersions:
    - "*"
    operations:
    - CREATE
    - UPDATE
  sideEffects: None
  timeoutSeconds: 10
