# https://github.com/kubernetes/ingress-nginx/issues/7118
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
patches:
- patch: |-
    - op: add
      path: /spec/ttlSecondsAfterFinished
      value: 30
  target:
    kind: Job
    name: ingress-nginx-admission-create
- patch: |-
    - op: add
      path: /spec/ttlSecondsAfterFinished
      value: 30
  target:
    kind: Job
    name: ingress-nginx-admission-patch
