apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: operations@appdat.jsc.nasa.gov # {"$kpt-set":"email"}
    server: https://acme-v02.api.letsencrypt.org/directory # {"$kpt-set":"issuer"}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
       ingress:
         class: nginx
