apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- cluster-issuer.yaml
secretGenerator:
- name: digitalocean-dns
  namespace: cert-manager
  behavior: create
  files:
  - access-token=secrets/access-token
patches:
- patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --default-issuer-name=$(DEFAULT_ISSUER_NAME)
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --default-issuer-kind=$(DEFAULT_ISSUER_KIND)
  target:
    kind: Deployment
    name: cert-manager
replacements:
- source:
    kind: ClusterIssuer
    name: letsencrypt
    fieldPath: kind
  targets:
  - select:
      kind: Deployment
      name: cert-manager
    fieldPaths:
    - spec.template.spec.containers.[name=cert-manager].env.[name=DEFAULT_ISSUER_KIND].value
    options:
      create: true
- source:
    kind: ClusterIssuer
    name: letsencrypt
    fieldPath: metadata.name
  targets:
  - select:
      kind: Deployment
      name: cert-manager
    fieldPaths:
    - spec.template.spec.containers.[name=cert-manager].env.[name=DEFAULT_ISSUER_NAME].value
    options:
      create: true
