apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- cluster-issuer.yaml
configurations:
- configurations.yaml
patches:
- patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --default-issuer-name=$(DEFAULT_ISSUER_NAME)
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --default-issuer-kind=ClusterIssuer
  target:
    kind: Deployment
    name: cert-manager
vars:
- name: DEFAULT_ISSUER_NAME
  fieldref:
    fieldpath: metadata.name
  objref:
    name: letsencrypt-prod
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
