apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
resources:
- manager.yaml
generatorOptions:
  disableNameSuffixHash: true
namespace: mongodb-operator
