# https://docs.gitlab.com/runner/configuration/advanced-configuration.html
concurrent = 10
check_interval = 30
log_level = "info"
log_format = "json"
listen_address = ':9252'

[[runners]]
  request_concurrency = 1
  output_limit = 8192

  # https://docs.gitlab.com/runner/configuration/feature-flags.html
  environment = [
    "FF_ENABLE_BASH_EXIT_CODE_CHECK=true",
    "FF_GITLAB_REGISTRY_HELPER_IMAGE=true",
    "FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY=false",
    "FF_USE_FASTZIP=true"
  ]

  # TODO: not sure why this
  # [runners.feature_flags]
  #   FF_ENABLE_BASH_EXIT_CODE_CHECK = true
  #   FF_GITLAB_REGISTRY_HELPER_IMAGE = true
  #   FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY = false
  #   FF_USE_FASTZIP = true
