# https://docs.gitlab.com/runner/configuration/advanced-configuration.html
concurrent = 10
check_interval = 30
log_level = "info"
log_format = "json"
listen_address = ':9252'

[[runners]]
  request_concurrency = 1
  output_limit = 8192

  # https://docs.gitlab.com/runner/configuration/feature-flags.html
  [runners.feature_flags]
    FF_GITLAB_REGISTRY_HELPER_IMAGE = true
    # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4119
    FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY = true
