apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configurations:
- https://appdat.jsc.nasa.gov/appdat/kpt-packages/-/raw/master/kustomizeconfig/ingress-nginx.yaml
configMapGenerator:
# https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
- name: ingress-nginx-controller
  behavior: merge
  literals:
  - add-headers=$(HEADERS_CONFIGMAP_NAMESPACE)/$(HEADERS_CONFIGMAP_NAME)
  - generate-request-id="true"
  - server-snippet="if ($server_name = "_") { return 444; }"
- name: ingress-nginx-custom-headers
  behavior: create
  literals:
  - X-Powered-By="zevisert"
vars:
- name: HEADERS_CONFIGMAP_NAME
  fieldref:
    fieldpath: metadata.name
  objref:
    name: ingress-nginx-custom-headers
    apiVersion: v1
    kind: ConfigMap
- name: HEADERS_CONFIGMAP_NAMESPACE
  fieldref:
    fieldpath: metadata.namespace
  objref:
    name: ingress-nginx-custom-headers
    apiVersion: v1
    kind: ConfigMap
