apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configurations:
- configmap-var-refs.yaml
configMapGenerator:
# https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
- name: ingress-nginx-controller
  behavior: create
  literals:
  - add-headers=$(HEADERS_CONFIGMAP_NAMESPACE)/$(HEADERS_CONFIGMAP_NAME)
  - enable-vts-status="true"
  - generate-request-id="true"
- name: ingress-nginx-custom-headers
  behavior: create
  literals:
  - X-Powered-By="appdat"
vars:
- name: HEADERS_CONFIGMAP_NAME
  fieldref:
    fieldpath: metadata.name
  objref:
    name: ingress-nginx-custom-headers
    apiVersion: v1
    kind: ConfigMap
- name: HEADERS_CONFIGMAP_NAMESPACE
  fieldref:
    fieldpath: metadata.namespace
  objref:
    name: ingress-nginx-custom-headers
    apiVersion: v1
    kind: ConfigMap
