# Source: gitlab-runner/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/port: "9252"
        prometheus.io/scrape: "true"
    spec:
      terminationGracePeriodSeconds: 3600
      serviceAccountName: gitlab-runner
      containers:
      - name: gitlab-runner
        image: registry.gitlab.com/gitlab-org/gitlab-runner:alpine-v13.12.0
        command: ["/bin/bash", "/scripts/entrypoint"]
        ports:
        - name: metrics
          containerPort: 9252
        env:
        - name: CI_SERVER_URL
          value: https://appdat.jsc.nasa.gov # {"$kpt-set":"runner.server"}
        - name: KUBERNETES_NAMESPACE
          value: appdat-system # {"$kpt-set":"runner.namespace"}
        - name: RUNNER_NAME
          value: default # {"$kpt-set":"runner.name"}
        - name: RUNNER_EXECUTOR
          value: kubernetes
        - name: RUNNER_LOCKED
          value: "false" # {"$kpt-set":"runner.locked"}
        - name: RUNNER_TAG_LIST
          value: "kubernetes, cluster" # {"$kpt-set":"runner.tags"}
        envFrom:
        - secretRef:
            name: gitlab-runner-tokens
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: secrets
          mountPath: /secrets
          readOnly: true
        - name: scripts
          mountPath: /scripts
        - name: etc-gitlab-runner
          mountPath: /home/gitlab-runner/.gitlab-runner
        livenessProbe:
          exec:
            command: ["/bin/bash", "/scripts/check-live"]
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command: ["/usr/bin/pgrep", "gitlab.*runner"]
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        lifecycle:
          preStop:
            exec:
              command: ["/entrypoint", "unregister", "--all-runners"]
        imagePullPolicy: "IfNotPresent"
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
      - name: secrets
        secret:
          secretName: gitlab-runner
      - name: scripts
        configMap:
          name: gitlab-runner
      - name: etc-gitlab-runner
        emptyDir:
          medium: "Memory"
      securityContext:
        fsGroup: 65533
        runAsUser: 100
