apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: default- # kpt-set: ${runner.name}-
images:
- name: registry.gitlab.com/gitlab-org/gitlab-runner:alpine
  newTag: alpine-v13.12.0 # kpt-set: alpine-${runner.version}
commonLabels:
  app.kubernetes.io/component: gitlab-runner
  app.kubernetes.io/managed-by: appdat
  app.kubernetes.io/name: default # kpt-set: ${runner.name}
labels:
- pairs:
    app.kubernetes.io/version: v13.12.0 # kpt-set: ${runner.version}
resources:
- deployment.yaml
- role-binding.yaml
- role.yaml
- service-account.yaml
configMapGenerator:
- name: gitlab-runner
  files:
  - config.toml=config/config.toml
  - config.template.toml=config/config.template.toml
  - check-live=config/check-live.sh
  - check-ready=config/check-ready.sh
  - entrypoint=config/entrypoint.sh
  - pre-entrypoint=config/pre-entrypoint.sh
  - register=config/register.sh
  - unregister=config/unregister.sh
secretGenerator:
- name: gitlab-runner
- name: gitlab-runner-tokens
  envs:
  - config/tokens.env
