# Source: gitlab-runner/templates/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-runner
roleRef:
  name: gitlab-runner
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: gitlab-runner
  kind: ServiceAccount
