# Source: gitlab-runner/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-runner-default # {"$kpt-set":"runner-name-subst"}
  labels:
    app: gitlab-runner-default # {"$kpt-set":"runner-name-subst"}
    chart: gitlab-runner-0.25.0
    release: "gitlab-runner"
    heritage: "Helm"
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
