# Source: gitlab-runner/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner-default # {"$kpt-set":"runner-name-subst"}
  labels:
    app: gitlab-runner-default # {"$kpt-set":"runner-name-subst"}
    chart: gitlab-runner-0.25.0
    release: "gitlab-runner"
    heritage: "Helm"
