apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
resources:
- deploy/clusterwide/role.yaml
- deploy/clusterwide/role_binding.yaml
- config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
- config/manager/manager.yaml
