apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/component: controller
  name: ingress-nginx-custom-headers
  namespace: ingress-nginx
data:
  # Add custom headers
  X-Powered-By: zevisert
  # Security
  X-Frame-Options: SAMEORIGIN
  X-Content-Type-Options: nosniff
  X-XSS-Protection: "1; mode: block"
  Referrer-Policy: strict-origin-when-cross-origin
