apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
namespace: ingress-nginx
resources:
  - upstream
components:
  - custom-config
  - geoip2
  - job-ttl
  - json-logs
  - security
patches:
  - patch: |-
      - op: replace
        path: /spec/externalTrafficPolicy
        value: Cluster
    target:
      kind: Service
      name: ingress-nginx-controller
