apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: appdat-system
resources:
- upstream
components:
- custom-config
- json-logs
- security
patches:
- patch: |-
    - op: replace
      path: /spec/externalTrafficPolicy
      value: Cluster
  target:
    kind: Service
    name: ingress-nginx-controller
- patch: |-
    - op: replace
      path: /kind
      value: DaemonSet
  target:
    kind: Deployment
    name: ingress-nginx-controller
