apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgo
  namespace: postgres-operator
  labels:
    app.kubernetes.io/name: pgo
    app.kubernetes.io/version: 5.0.5
    postgres-operator.crunchydata.com/control-plane: postgres-operator
