apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: /pgo
  name: pgo
  namespace: postgres-operator
  labels:
    app.kubernetes.io/name: pgo
    app.kubernetes.io/version: 5.3.0
    postgres-operator.crunchydata.com/control-plane: postgres-operator
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|default|pgo'
