apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: postgres-operator/pgo
  name: pgo
  namespace: postgres-operator
  labels:
    app.kubernetes.io/name: pgo
    app.kubernetes.io/version: 5.2.0
    postgres-operator.crunchydata.com/control-plane: postgres-operator
