# Source: cert-manager/templates/startupapicheck-rbac.yaml
# create certificate role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-startupapicheck:create-cert
  namespace: cert-manager
  labels:
    app: startupapicheck
    app.kubernetes.io/name: startupapicheck
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/component: startupapicheck
    app.kubernetes.io/version: v1.6.1
    app.kubernetes.io/managed-by: kpt
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
