apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../appdat
configMapGenerator:
# https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
- name: ingress-nginx-controller
  behavior: merge
  literals:
  - use-proxy-protocol="true"
  - real-ip-header=proxy_protocol
patches:
- path: service-patch.yaml
  target:
    kind: Service
    name: ingress-nginx-controller
