kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata: # kpt-merge: /mongodb-kubernetes-operator
  name: mongodb-kubernetes-operator
subjects:
- kind: ServiceAccount
  namespace: mongodb-operator # kpt-set: ${operator.namespace}
  name: mongodb-kubernetes-operator
roleRef:
  kind: ClusterRole
  name: mongodb-kubernetes-operator
  apiGroup: rbac.authorization.k8s.io
