apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        # ^v0.10 requires >= kube 1.22
        image: k8s.gcr.io/external-dns/external-dns:v0.9.0
        args:
        - --registry=txt
        - --source=service
        - --source=ingress
        - --domain-filter=isert.link
        - --domain-filter=isert.ca
        - --domain-filter=zevisert.ca
        - --domain-filter=zuzi.art
        - --domain-filter=zuzanariha.art
        - --provider=digitalocean
        env:
        - name: DO_TOKEN
          valueFrom:
            secretKeyRef:
              key: access-token
              name: digitalocean-dns
