apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
secretGenerator:
- name: gitlab-runner
  files:
  - runner-registration-token=secrets/registration.token
  - runner-token=secrets/runner.token
  behavior: merge
