apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
secretGenerator:
- name: gitlab-runner-default # {"$kpt-set":"runner-name-subst"}
  files:
  - runner-registration-token=secrets/registration.token
  - runner-token=secrets/runner.token
  behavior: merge
