apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - upstream
openapi:
  # This is necessary to ensure kustomize knows ClusterIssuer is a
  # cluster scoped resource
  path: .schemas/schema.json
crds:
  # This is necessary to ensure kustomize knows ClusterIssuer substitutes
  # fields like privateKeySecretRef with secretRefs. It would otherwise not
  # know the field referenced a K8 secret resource. This replicates the
  # behavior previously provided by 'configurations'
  - .schemas/crd.json
components:
  - default-issuer
  - account-key
