kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata: # kpt-merge: /mongodb-kubernetes-operator
  name: mongodb-kubernetes-operator
  namespace: mongodb-operator # kpt-set: ${operator.namespace}
subjects:
- kind: ServiceAccount
  name: mongodb-kubernetes-operator
roleRef:
  kind: Role
  name: mongodb-kubernetes-operator
  apiGroup: rbac.authorization.k8s.io
