kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata: # kpt-merge: /mongodb-database
  name: mongodb-database
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
      - delete
      - get
